### ISSUE TITLE
candybar fails to build with '-Werror' flag

### ISSUE THREAD

**Issue by phijor** [Lokaltog/candybar#104] opened 2015-04-18 18:28 UTC
I am trying to build candybar from the [AUR](https://aur.archlinux.org/packages/candybar-git/) on ArchLinux.

As it builds, it issues the complaint that `GListStore` is being redefined.

```
    [...]
/usr/include/glib-2.0/gio/gliststore.h:36:22: error: redefinition of typedef GListStore [-Werror=pedantic]
 G_DECLARE_FINAL_TYPE(GListStore, g_list_store, G, LIST_STORE, GObject)
                      ^
/usr/include/glib-2.0/gobject/gtype.h:1390:35: note: in definition of macro G_DECLARE_FINAL_TYPE
   typedef struct _##ModuleObjName ModuleObjName;                                                         \
                                   ^
In file included from /usr/include/glib-2.0/gio/gio.h:26:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /usr/include/webkitgtk-3.0/webkit/webkitglobals.h:28,
                 from /usr/include/webkitgtk-3.0/webkit/webkitenumtypes.h:63,
                 from /usr/include/webkitgtk-3.0/webkit/webkit.h:29,
                 from /home/phijor/git/cnd2/src/widgets.h:11,
                 from ../src/widgets/volume.c:1:
/usr/include/glib-2.0/gio/giotypes.h:65:47: note: previous declaration of GListStore was here
 typedef struct _GListStore                    GListStore;
                                               ^
cc1: all warnings being treated as errors
    [...]
```

(full log [here](http://pastebin.com/ZUd62hem))

However, after removing the
`-Werror` flag from [wscript@line46](https://github.com/Lokaltog/candybar/blob/develop/wscript#L46), the build completes just fine.

I know that `-Werror` only [makes warnings into errors](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html), so while removing it from the build-options allows me to compile, I don't know if there might still be something wrong in the final build.
 edited out the flag.
If you are sure that all warnings issued by the compiler are harmless, would you consider removing `-Werror` so that people building from AUR can have the issue fixed upstream? Having to edit the actual repository locally feels a bit cumbersome when using AUR-helpers like `yaourt`, because in order to still install the dependencies alongside candybar, you have to point the `PKGBUILD` to said custom local repository that has the flag edited out.

(I hope I have made myself clear, English isn't my first langue, so please excuse me)

**Comment by Lokaltog** [comment] 2015-04-20 07:16
This is a glib2 issue that appears to have been [rolled back](https://git.gnome.org/browse/glib/commit/?id=4a292721bcf2943bfc05c6a1c859992f28e3efec). If you update glib2 you should be able to build candybar from the AUR without any problems. I'm running glib2 2.42.2-1 and I'm not able to reproduce this error.

**Comment by mmetak** [comment] 2015-04-24 02:04
I can also confirm this issue on Archlinux with glib2-2.44.0-1 on two separate machines.

**Comment by phijor** [comment] 2015-04-25 12:53
So I thougt I was going crazy, but appearently, `glib2-2.44.0-1` on Arch does not include the patch Lokaltok mentioned.

What I did to make sure that the patch is indeed not in the package:
1. Download glib2 from from archlinux.org,
   [here](https://www.archlinux.org/packages/core/x86_64/glib2/download/)
2. `untar` and open `./usr/include/glib-2.0/gio/giotypes.h`
3. Look at lines 62-65 and compare with the diff Lokaltok linked earlier.
4. See that that `GListModel` and `GListStore` are still typedef'd, eventhough they shoudn't be.

I am using glib2-git from the AUR now, and everything builds fine. I think I
might have to contact the Arch glib2-maintainer. Who knows what the reason is that the patch is not being distributed.

**Comment by Lokaltog** [comment] 2015-04-25 15:23
Yeah, that's a bit strange that they haven't included this patch on Arch. I can reproduce this with the latest glib2 as well.

There are a couple of solutions we could do for candybar, one is to build with `-c11` (it's mentioned in the patch notes that type redifiniton is a C11 feature). We could also remove the `-Werror` flag from the production build, although I'd prefer to avoid that. Another possible (temporary) solution is that you could build the debug version, which doesn't include this flag by default.

It currently builds fine with the `-c11` flag with glib2-2.44.0-1. I'm not an experienced C developer, so I'd like to hear your thoughts on this, would it work to use the `-c11` when building, or is this kind of a bleeding edge feature in gcc that would break the building process on non-rolling release distros like e.g. Debian?

**Comment by phijor** [comment] 2015-04-25 18:42
I am by no means an experienced developer (heck, I'm self-taught and only doing this in the limited time I have to spare), thus I think I may be the wrong person to ask for opinions. But this is what I think about your proposals:
1. I would not risk building with `-c11`, as I know the consequences across distros as bad as you. C11 does not seem to be widely implemented. Type-redefinition appears to be legal in C++, but we would be driving nails in with a sledgehammer if we started to build wit `g++` just for this feature.
2. `-Werror` should stay. Even tough annoying in this case, I think it's not worth dropping an option that made us aware of a bug. Who knows what future bugs we could miss without it.

My proposal: Create a new branch that is Arch-specific (e.g. `develop-arch`). Have it include `-c11`, as it seems to be implemented in `gcc` on Arch. Edit `_gitbranch` in the PKGBUILD to point to the new branch. Contact the maintainer(s) of glib2 to inform them of this issue. Comment on the AUR-page why the changes were made, so no one gets confused why a distro-specific branch was introduced. This allows Arch-users to build, everyone else just get's the vanilla-experience of branch `develop` without issues _and_ we can keep `-Werror` for everyone.

What do you think?

**Comment by sullyj3** [comment] 2015-06-01 12:36
I'm on arch. I had the same issue, just ran pacman -Syu, and it seems to be working now. I'm on glib2 v 2.44.1-1

**Comment by phijor** [comment] 2015-06-02 13:54
Can confim, `pacman -Qi glib2` says I'm on `v2.44.1-1` and candybar builds without any errors.

Also, `giotypes.h` from `/usr/include/glib-2.0/gio/` doesn't typedef `GListModel` and `GListStore` anymore. Do you think this issue can be closed?

**Comment by Lokaltog** [comment] 2015-06-02 14:06
Sorry about the delayed feedback on this issue. Since this appears to be an Arch-specific problem that has been resolved in glib I think it's fine to close this issue. It's a rolling release distro after all, and candybar is kind of experimental, so I think the better solution is to just ask Arch users to run pacman -Syu than adding Arch-specific build flags to the PKGBUILD.

**Closed as completed by Lokaltog** 2015-06-02 14:06 UTC
Labels: bug
